### ISSUE TITLE
nightly clang libcxx build failing

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-oncall#72]
## Overview

The clang libcxx build is failing on building ament_index_cpp, in the linker for rcpputils -> rcutils

```
12:21:24 /usr/bin/ld: warning: librcutils.so, needed by /home/jenkins-agent/workspace/nightly_linux_clang_libcxx/ws/install/rcpputils/lib/librcpputils.so, not found (try using -rpath or -rpath-link)
12:21:24 /home/jenkins-agent/workspace/nightly_linux_clang_libcxx/ws/install/rcpputils/lib/librcpputils.so: undefined reference to `rcutils_get_env'
12:21:24 /home/jenkins-agent/workspace/nightly_linux_clang_libcxx/ws/install/rcpputils/lib/librcpputils.so: undefined reference to `rcutils_is_file'
```

## Required Information

* **Job Home**: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/317
* **Latest Failing Build** (try to keep this up to date): https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/327/
* **External tracking ticket**: https://github.com/ros2/tinyxml_vendor/issues/15

**Comment by thomas-moulard** [comment]
I would prioritize this ticket, this sounds like a real bug.

**Comment by dabonnie** [comment]
I'm currently trying to reproduce.

**Comment by dabonnie** [comment]
Latest builds are failing (locally reproducible) because timyxml vendor cannot resolve a remote resource:

```
         --- LOG BEGIN ---
           Trying 209.61.193.20...

  TCP_NODELAY set

  connect to 209.61.193.20 port 443 failed: Connection timed out

  Failed to connect to superb-dca2.dl.sourceforge.net port 443: Connection
  timed out

  Closing connection 0



         --- LOG END ---
         error: downloading 'https://superb-dca2.dl.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz' failed
         status_code: 7
         status_string: "Couldn't connect to server"
         log:
```

**Comment by dabonnie** [comment]
Opened: https://github.com/ros2/tinyxml_vendor/issues/15

**Comment by emersonknapp** [comment]
That issue is fixed, perhaps you can try building up through rcpputils now

**Comment by dabonnie** [comment]
Nightly [327](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/327/) is still failing.

**Comment by prajakta-gokhale** [comment]
This has been fixed and build is back to green.
